// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// TransactionHistory is the predicate function for transactionhistory builders.
type TransactionHistory func(*sql.Selector)

// Transfer is the predicate function for transfer builders.
type Transfer func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAccount is the predicate function for useraccount builders.
type UserAccount func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)
