// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LoginToken is the predicate function for logintoken builders.
type LoginToken func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAccount is the predicate function for useraccount builders.
type UserAccount func(*sql.Selector)
