// Code generated by ent, DO NOT EDIT.

package useraccount

import (
	"comb.com/banking/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldID, id))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldBalance, v))
}

// AccountNumber applies equality check predicate on the "account_number" field. It's identical to AccountNumberEQ.
func AccountNumber(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldBalance, v))
}

// AccountNumberEQ applies the EQ predicate on the "account_number" field.
func AccountNumberEQ(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountNumberNEQ applies the NEQ predicate on the "account_number" field.
func AccountNumberNEQ(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldAccountNumber, v))
}

// AccountNumberIn applies the In predicate on the "account_number" field.
func AccountNumberIn(vs ...int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldAccountNumber, vs...))
}

// AccountNumberNotIn applies the NotIn predicate on the "account_number" field.
func AccountNumberNotIn(vs ...int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldAccountNumber, vs...))
}

// AccountNumberGT applies the GT predicate on the "account_number" field.
func AccountNumberGT(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldAccountNumber, v))
}

// AccountNumberGTE applies the GTE predicate on the "account_number" field.
func AccountNumberGTE(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldAccountNumber, v))
}

// AccountNumberLT applies the LT predicate on the "account_number" field.
func AccountNumberLT(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldAccountNumber, v))
}

// AccountNumberLTE applies the LTE predicate on the "account_number" field.
func AccountNumberLTE(v int64) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldAccountNumber, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransactions applies the HasEdge predicate on the "transactions" edge.
func HasTransactions() predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionsWith applies the HasEdge predicate on the "transactions" edge with a given conditions (other predicates).
func HasTransactionsWith(preds ...predicate.Transaction) predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := newTransactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOutgoingTransfers applies the HasEdge predicate on the "outgoing_transfers" edge.
func HasOutgoingTransfers() predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OutgoingTransfersTable, OutgoingTransfersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOutgoingTransfersWith applies the HasEdge predicate on the "outgoing_transfers" edge with a given conditions (other predicates).
func HasOutgoingTransfersWith(preds ...predicate.Transfer) predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := newOutgoingTransfersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIncomingTransfers applies the HasEdge predicate on the "incoming_transfers" edge.
func HasIncomingTransfers() predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IncomingTransfersTable, IncomingTransfersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIncomingTransfersWith applies the HasEdge predicate on the "incoming_transfers" edge with a given conditions (other predicates).
func HasIncomingTransfersWith(preds ...predicate.Transfer) predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := newIncomingTransfersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountNumberID applies the HasEdge predicate on the "account_number_id" edge.
func HasAccountNumberID() predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountNumberIDTable, AccountNumberIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountNumberIDWith applies the HasEdge predicate on the "account_number_id" edge with a given conditions (other predicates).
func HasAccountNumberIDWith(preds ...predicate.TransactionHistory) predicate.UserAccount {
	return predicate.UserAccount(func(s *sql.Selector) {
		step := newAccountNumberIDStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAccount) predicate.UserAccount {
	return predicate.UserAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAccount) predicate.UserAccount {
	return predicate.UserAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAccount) predicate.UserAccount {
	return predicate.UserAccount(sql.NotPredicates(p))
}
