// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"comb.com/banking/ent/logintoken"
	"comb.com/banking/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LoginToken is the model entity for the LoginToken schema.
type LoginToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// Expiredtime holds the value of the "expiredtime" field.
	Expiredtime time.Time `json:"expiredtime,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoginTokenQuery when eager-loading is set.
	Edges        LoginTokenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LoginTokenEdges holds the relations/edges for other nodes in the graph.
type LoginTokenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoginTokenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case logintoken.FieldID:
			values[i] = new(sql.NullInt64)
		case logintoken.FieldToken:
			values[i] = new(sql.NullString)
		case logintoken.FieldExpiredtime, logintoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginToken fields.
func (lt *LoginToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case logintoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lt.ID = int(value.Int64)
		case logintoken.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				lt.Token = value.String
			}
		case logintoken.FieldExpiredtime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiredtime", values[i])
			} else if value.Valid {
				lt.Expiredtime = value.Time
			}
		case logintoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				lt.CreatedAt = value.Time
			}
		default:
			lt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginToken.
// This includes values selected through modifiers, order, etc.
func (lt *LoginToken) Value(name string) (ent.Value, error) {
	return lt.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the LoginToken entity.
func (lt *LoginToken) QueryUser() *UserQuery {
	return NewLoginTokenClient(lt.config).QueryUser(lt)
}

// Update returns a builder for updating this LoginToken.
// Note that you need to call LoginToken.Unwrap() before calling this method if this LoginToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (lt *LoginToken) Update() *LoginTokenUpdateOne {
	return NewLoginTokenClient(lt.config).UpdateOne(lt)
}

// Unwrap unwraps the LoginToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lt *LoginToken) Unwrap() *LoginToken {
	_tx, ok := lt.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginToken is not a transactional entity")
	}
	lt.config.driver = _tx.drv
	return lt
}

// String implements the fmt.Stringer.
func (lt *LoginToken) String() string {
	var builder strings.Builder
	builder.WriteString("LoginToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lt.ID))
	builder.WriteString("token=")
	builder.WriteString(lt.Token)
	builder.WriteString(", ")
	builder.WriteString("expiredtime=")
	builder.WriteString(lt.Expiredtime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(lt.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LoginTokens is a parsable slice of LoginToken.
type LoginTokens []*LoginToken
