// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"comb.com/banking/ent/schema"
	"comb.com/banking/ent/token"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescExpiredtime is the schema descriptor for expiredtime field.
	tokenDescExpiredtime := tokenFields[2].Descriptor()
	// token.DefaultExpiredtime holds the default value on creation for the expiredtime field.
	token.DefaultExpiredtime = tokenDescExpiredtime.Default.(func() time.Time)
	// tokenDescIsUsing is the schema descriptor for is_using field.
	tokenDescIsUsing := tokenFields[3].Descriptor()
	// token.DefaultIsUsing holds the default value on creation for the is_using field.
	token.DefaultIsUsing = tokenDescIsUsing.Default.(bool)
}
