// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"comb.com/banking/ent/predicate"
	"comb.com/banking/ent/transfer"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransferUpdate is the builder for updating Transfer entities.
type TransferUpdate struct {
	config
	hooks    []Hook
	mutation *TransferMutation
}

// Where appends a list predicates to the TransferUpdate builder.
func (tu *TransferUpdate) Where(ps ...predicate.Transfer) *TransferUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTransactionTime sets the "TransactionTime" field.
func (tu *TransferUpdate) SetTransactionTime(t time.Time) *TransferUpdate {
	tu.mutation.SetTransactionTime(t)
	return tu
}

// SetNillableTransactionTime sets the "TransactionTime" field if the given value is not nil.
func (tu *TransferUpdate) SetNillableTransactionTime(t *time.Time) *TransferUpdate {
	if t != nil {
		tu.SetTransactionTime(*t)
	}
	return tu
}

// SetFrom sets the "From" field.
func (tu *TransferUpdate) SetFrom(i int) *TransferUpdate {
	tu.mutation.ResetFrom()
	tu.mutation.SetFrom(i)
	return tu
}

// SetNillableFrom sets the "From" field if the given value is not nil.
func (tu *TransferUpdate) SetNillableFrom(i *int) *TransferUpdate {
	if i != nil {
		tu.SetFrom(*i)
	}
	return tu
}

// AddFrom adds i to the "From" field.
func (tu *TransferUpdate) AddFrom(i int) *TransferUpdate {
	tu.mutation.AddFrom(i)
	return tu
}

// SetTo sets the "To" field.
func (tu *TransferUpdate) SetTo(i int) *TransferUpdate {
	tu.mutation.ResetTo()
	tu.mutation.SetTo(i)
	return tu
}

// SetNillableTo sets the "To" field if the given value is not nil.
func (tu *TransferUpdate) SetNillableTo(i *int) *TransferUpdate {
	if i != nil {
		tu.SetTo(*i)
	}
	return tu
}

// AddTo adds i to the "To" field.
func (tu *TransferUpdate) AddTo(i int) *TransferUpdate {
	tu.mutation.AddTo(i)
	return tu
}

// SetAmount sets the "Amount" field.
func (tu *TransferUpdate) SetAmount(i int) *TransferUpdate {
	tu.mutation.ResetAmount()
	tu.mutation.SetAmount(i)
	return tu
}

// SetNillableAmount sets the "Amount" field if the given value is not nil.
func (tu *TransferUpdate) SetNillableAmount(i *int) *TransferUpdate {
	if i != nil {
		tu.SetAmount(*i)
	}
	return tu
}

// AddAmount adds i to the "Amount" field.
func (tu *TransferUpdate) AddAmount(i int) *TransferUpdate {
	tu.mutation.AddAmount(i)
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TransferUpdate) SetCreatedAt(t time.Time) *TransferUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TransferUpdate) SetNillableCreatedAt(t *time.Time) *TransferUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TransferUpdate) SetUpdatedAt(t time.Time) *TransferUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// Mutation returns the TransferMutation object of the builder.
func (tu *TransferUpdate) Mutation() *TransferMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransferUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransferUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransferUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransferUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TransferUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := transfer.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

func (tu *TransferUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(transfer.Table, transfer.Columns, sqlgraph.NewFieldSpec(transfer.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.TransactionTime(); ok {
		_spec.SetField(transfer.FieldTransactionTime, field.TypeTime, value)
	}
	if value, ok := tu.mutation.From(); ok {
		_spec.SetField(transfer.FieldFrom, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedFrom(); ok {
		_spec.AddField(transfer.FieldFrom, field.TypeInt, value)
	}
	if value, ok := tu.mutation.To(); ok {
		_spec.SetField(transfer.FieldTo, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedTo(); ok {
		_spec.AddField(transfer.FieldTo, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Amount(); ok {
		_spec.SetField(transfer.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedAmount(); ok {
		_spec.AddField(transfer.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.SetField(transfer.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(transfer.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TransferUpdateOne is the builder for updating a single Transfer entity.
type TransferUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransferMutation
}

// SetTransactionTime sets the "TransactionTime" field.
func (tuo *TransferUpdateOne) SetTransactionTime(t time.Time) *TransferUpdateOne {
	tuo.mutation.SetTransactionTime(t)
	return tuo
}

// SetNillableTransactionTime sets the "TransactionTime" field if the given value is not nil.
func (tuo *TransferUpdateOne) SetNillableTransactionTime(t *time.Time) *TransferUpdateOne {
	if t != nil {
		tuo.SetTransactionTime(*t)
	}
	return tuo
}

// SetFrom sets the "From" field.
func (tuo *TransferUpdateOne) SetFrom(i int) *TransferUpdateOne {
	tuo.mutation.ResetFrom()
	tuo.mutation.SetFrom(i)
	return tuo
}

// SetNillableFrom sets the "From" field if the given value is not nil.
func (tuo *TransferUpdateOne) SetNillableFrom(i *int) *TransferUpdateOne {
	if i != nil {
		tuo.SetFrom(*i)
	}
	return tuo
}

// AddFrom adds i to the "From" field.
func (tuo *TransferUpdateOne) AddFrom(i int) *TransferUpdateOne {
	tuo.mutation.AddFrom(i)
	return tuo
}

// SetTo sets the "To" field.
func (tuo *TransferUpdateOne) SetTo(i int) *TransferUpdateOne {
	tuo.mutation.ResetTo()
	tuo.mutation.SetTo(i)
	return tuo
}

// SetNillableTo sets the "To" field if the given value is not nil.
func (tuo *TransferUpdateOne) SetNillableTo(i *int) *TransferUpdateOne {
	if i != nil {
		tuo.SetTo(*i)
	}
	return tuo
}

// AddTo adds i to the "To" field.
func (tuo *TransferUpdateOne) AddTo(i int) *TransferUpdateOne {
	tuo.mutation.AddTo(i)
	return tuo
}

// SetAmount sets the "Amount" field.
func (tuo *TransferUpdateOne) SetAmount(i int) *TransferUpdateOne {
	tuo.mutation.ResetAmount()
	tuo.mutation.SetAmount(i)
	return tuo
}

// SetNillableAmount sets the "Amount" field if the given value is not nil.
func (tuo *TransferUpdateOne) SetNillableAmount(i *int) *TransferUpdateOne {
	if i != nil {
		tuo.SetAmount(*i)
	}
	return tuo
}

// AddAmount adds i to the "Amount" field.
func (tuo *TransferUpdateOne) AddAmount(i int) *TransferUpdateOne {
	tuo.mutation.AddAmount(i)
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TransferUpdateOne) SetCreatedAt(t time.Time) *TransferUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TransferUpdateOne) SetNillableCreatedAt(t *time.Time) *TransferUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TransferUpdateOne) SetUpdatedAt(t time.Time) *TransferUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// Mutation returns the TransferMutation object of the builder.
func (tuo *TransferUpdateOne) Mutation() *TransferMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TransferUpdate builder.
func (tuo *TransferUpdateOne) Where(ps ...predicate.Transfer) *TransferUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransferUpdateOne) Select(field string, fields ...string) *TransferUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transfer entity.
func (tuo *TransferUpdateOne) Save(ctx context.Context) (*Transfer, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransferUpdateOne) SaveX(ctx context.Context) *Transfer {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransferUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransferUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TransferUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := transfer.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

func (tuo *TransferUpdateOne) sqlSave(ctx context.Context) (_node *Transfer, err error) {
	_spec := sqlgraph.NewUpdateSpec(transfer.Table, transfer.Columns, sqlgraph.NewFieldSpec(transfer.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transfer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transfer.FieldID)
		for _, f := range fields {
			if !transfer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.TransactionTime(); ok {
		_spec.SetField(transfer.FieldTransactionTime, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.From(); ok {
		_spec.SetField(transfer.FieldFrom, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedFrom(); ok {
		_spec.AddField(transfer.FieldFrom, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.To(); ok {
		_spec.SetField(transfer.FieldTo, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedTo(); ok {
		_spec.AddField(transfer.FieldTo, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Amount(); ok {
		_spec.SetField(transfer.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedAmount(); ok {
		_spec.AddField(transfer.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.SetField(transfer.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(transfer.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Transfer{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
