// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"comb.com/banking/ent/predicate"
	"comb.com/banking/ent/userprofile"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserProfileUpdate is the builder for updating UserProfile entities.
type UserProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserProfileMutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (upu *UserProfileUpdate) Where(ps ...predicate.UserProfile) *UserProfileUpdate {
	upu.mutation.Where(ps...)
	return upu
}

// SetFirstname sets the "firstname" field.
func (upu *UserProfileUpdate) SetFirstname(s string) *UserProfileUpdate {
	upu.mutation.SetFirstname(s)
	return upu
}

// SetNillableFirstname sets the "firstname" field if the given value is not nil.
func (upu *UserProfileUpdate) SetNillableFirstname(s *string) *UserProfileUpdate {
	if s != nil {
		upu.SetFirstname(*s)
	}
	return upu
}

// SetLastname sets the "lastname" field.
func (upu *UserProfileUpdate) SetLastname(s string) *UserProfileUpdate {
	upu.mutation.SetLastname(s)
	return upu
}

// SetNillableLastname sets the "lastname" field if the given value is not nil.
func (upu *UserProfileUpdate) SetNillableLastname(s *string) *UserProfileUpdate {
	if s != nil {
		upu.SetLastname(*s)
	}
	return upu
}

// SetCmnd sets the "cmnd" field.
func (upu *UserProfileUpdate) SetCmnd(s string) *UserProfileUpdate {
	upu.mutation.SetCmnd(s)
	return upu
}

// SetNillableCmnd sets the "cmnd" field if the given value is not nil.
func (upu *UserProfileUpdate) SetNillableCmnd(s *string) *UserProfileUpdate {
	if s != nil {
		upu.SetCmnd(*s)
	}
	return upu
}

// SetAddress sets the "address" field.
func (upu *UserProfileUpdate) SetAddress(s string) *UserProfileUpdate {
	upu.mutation.SetAddress(s)
	return upu
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (upu *UserProfileUpdate) SetNillableAddress(s *string) *UserProfileUpdate {
	if s != nil {
		upu.SetAddress(*s)
	}
	return upu
}

// SetGender sets the "gender" field.
func (upu *UserProfileUpdate) SetGender(b bool) *UserProfileUpdate {
	upu.mutation.SetGender(b)
	return upu
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (upu *UserProfileUpdate) SetNillableGender(b *bool) *UserProfileUpdate {
	if b != nil {
		upu.SetGender(*b)
	}
	return upu
}

// SetBirthday sets the "birthday" field.
func (upu *UserProfileUpdate) SetBirthday(s string) *UserProfileUpdate {
	upu.mutation.SetBirthday(s)
	return upu
}

// SetNillableBirthday sets the "birthday" field if the given value is not nil.
func (upu *UserProfileUpdate) SetNillableBirthday(s *string) *UserProfileUpdate {
	if s != nil {
		upu.SetBirthday(*s)
	}
	return upu
}

// SetCreatedAt sets the "created_at" field.
func (upu *UserProfileUpdate) SetCreatedAt(t time.Time) *UserProfileUpdate {
	upu.mutation.SetCreatedAt(t)
	return upu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (upu *UserProfileUpdate) SetNillableCreatedAt(t *time.Time) *UserProfileUpdate {
	if t != nil {
		upu.SetCreatedAt(*t)
	}
	return upu
}

// SetUpdatedAt sets the "updated_at" field.
func (upu *UserProfileUpdate) SetUpdatedAt(t time.Time) *UserProfileUpdate {
	upu.mutation.SetUpdatedAt(t)
	return upu
}

// Mutation returns the UserProfileMutation object of the builder.
func (upu *UserProfileUpdate) Mutation() *UserProfileMutation {
	return upu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (upu *UserProfileUpdate) Save(ctx context.Context) (int, error) {
	upu.defaults()
	return withHooks(ctx, upu.sqlSave, upu.mutation, upu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upu *UserProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := upu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (upu *UserProfileUpdate) Exec(ctx context.Context) error {
	_, err := upu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upu *UserProfileUpdate) ExecX(ctx context.Context) {
	if err := upu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (upu *UserProfileUpdate) defaults() {
	if _, ok := upu.mutation.UpdatedAt(); !ok {
		v := userprofile.UpdateDefaultUpdatedAt()
		upu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upu *UserProfileUpdate) check() error {
	if v, ok := upu.mutation.Firstname(); ok {
		if err := userprofile.FirstnameValidator(v); err != nil {
			return &ValidationError{Name: "firstname", err: fmt.Errorf(`ent: validator failed for field "UserProfile.firstname": %w`, err)}
		}
	}
	if v, ok := upu.mutation.Lastname(); ok {
		if err := userprofile.LastnameValidator(v); err != nil {
			return &ValidationError{Name: "lastname", err: fmt.Errorf(`ent: validator failed for field "UserProfile.lastname": %w`, err)}
		}
	}
	if v, ok := upu.mutation.Cmnd(); ok {
		if err := userprofile.CmndValidator(v); err != nil {
			return &ValidationError{Name: "cmnd", err: fmt.Errorf(`ent: validator failed for field "UserProfile.cmnd": %w`, err)}
		}
	}
	if v, ok := upu.mutation.Address(); ok {
		if err := userprofile.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "UserProfile.address": %w`, err)}
		}
	}
	if v, ok := upu.mutation.Birthday(); ok {
		if err := userprofile.BirthdayValidator(v); err != nil {
			return &ValidationError{Name: "birthday", err: fmt.Errorf(`ent: validator failed for field "UserProfile.birthday": %w`, err)}
		}
	}
	return nil
}

func (upu *UserProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := upu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt))
	if ps := upu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upu.mutation.Firstname(); ok {
		_spec.SetField(userprofile.FieldFirstname, field.TypeString, value)
	}
	if value, ok := upu.mutation.Lastname(); ok {
		_spec.SetField(userprofile.FieldLastname, field.TypeString, value)
	}
	if value, ok := upu.mutation.Cmnd(); ok {
		_spec.SetField(userprofile.FieldCmnd, field.TypeString, value)
	}
	if value, ok := upu.mutation.Address(); ok {
		_spec.SetField(userprofile.FieldAddress, field.TypeString, value)
	}
	if value, ok := upu.mutation.Gender(); ok {
		_spec.SetField(userprofile.FieldGender, field.TypeBool, value)
	}
	if value, ok := upu.mutation.Birthday(); ok {
		_spec.SetField(userprofile.FieldBirthday, field.TypeString, value)
	}
	if value, ok := upu.mutation.CreatedAt(); ok {
		_spec.SetField(userprofile.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := upu.mutation.UpdatedAt(); ok {
		_spec.SetField(userprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, upu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	upu.mutation.done = true
	return n, nil
}

// UserProfileUpdateOne is the builder for updating a single UserProfile entity.
type UserProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserProfileMutation
}

// SetFirstname sets the "firstname" field.
func (upuo *UserProfileUpdateOne) SetFirstname(s string) *UserProfileUpdateOne {
	upuo.mutation.SetFirstname(s)
	return upuo
}

// SetNillableFirstname sets the "firstname" field if the given value is not nil.
func (upuo *UserProfileUpdateOne) SetNillableFirstname(s *string) *UserProfileUpdateOne {
	if s != nil {
		upuo.SetFirstname(*s)
	}
	return upuo
}

// SetLastname sets the "lastname" field.
func (upuo *UserProfileUpdateOne) SetLastname(s string) *UserProfileUpdateOne {
	upuo.mutation.SetLastname(s)
	return upuo
}

// SetNillableLastname sets the "lastname" field if the given value is not nil.
func (upuo *UserProfileUpdateOne) SetNillableLastname(s *string) *UserProfileUpdateOne {
	if s != nil {
		upuo.SetLastname(*s)
	}
	return upuo
}

// SetCmnd sets the "cmnd" field.
func (upuo *UserProfileUpdateOne) SetCmnd(s string) *UserProfileUpdateOne {
	upuo.mutation.SetCmnd(s)
	return upuo
}

// SetNillableCmnd sets the "cmnd" field if the given value is not nil.
func (upuo *UserProfileUpdateOne) SetNillableCmnd(s *string) *UserProfileUpdateOne {
	if s != nil {
		upuo.SetCmnd(*s)
	}
	return upuo
}

// SetAddress sets the "address" field.
func (upuo *UserProfileUpdateOne) SetAddress(s string) *UserProfileUpdateOne {
	upuo.mutation.SetAddress(s)
	return upuo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (upuo *UserProfileUpdateOne) SetNillableAddress(s *string) *UserProfileUpdateOne {
	if s != nil {
		upuo.SetAddress(*s)
	}
	return upuo
}

// SetGender sets the "gender" field.
func (upuo *UserProfileUpdateOne) SetGender(b bool) *UserProfileUpdateOne {
	upuo.mutation.SetGender(b)
	return upuo
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (upuo *UserProfileUpdateOne) SetNillableGender(b *bool) *UserProfileUpdateOne {
	if b != nil {
		upuo.SetGender(*b)
	}
	return upuo
}

// SetBirthday sets the "birthday" field.
func (upuo *UserProfileUpdateOne) SetBirthday(s string) *UserProfileUpdateOne {
	upuo.mutation.SetBirthday(s)
	return upuo
}

// SetNillableBirthday sets the "birthday" field if the given value is not nil.
func (upuo *UserProfileUpdateOne) SetNillableBirthday(s *string) *UserProfileUpdateOne {
	if s != nil {
		upuo.SetBirthday(*s)
	}
	return upuo
}

// SetCreatedAt sets the "created_at" field.
func (upuo *UserProfileUpdateOne) SetCreatedAt(t time.Time) *UserProfileUpdateOne {
	upuo.mutation.SetCreatedAt(t)
	return upuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (upuo *UserProfileUpdateOne) SetNillableCreatedAt(t *time.Time) *UserProfileUpdateOne {
	if t != nil {
		upuo.SetCreatedAt(*t)
	}
	return upuo
}

// SetUpdatedAt sets the "updated_at" field.
func (upuo *UserProfileUpdateOne) SetUpdatedAt(t time.Time) *UserProfileUpdateOne {
	upuo.mutation.SetUpdatedAt(t)
	return upuo
}

// Mutation returns the UserProfileMutation object of the builder.
func (upuo *UserProfileUpdateOne) Mutation() *UserProfileMutation {
	return upuo.mutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (upuo *UserProfileUpdateOne) Where(ps ...predicate.UserProfile) *UserProfileUpdateOne {
	upuo.mutation.Where(ps...)
	return upuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (upuo *UserProfileUpdateOne) Select(field string, fields ...string) *UserProfileUpdateOne {
	upuo.fields = append([]string{field}, fields...)
	return upuo
}

// Save executes the query and returns the updated UserProfile entity.
func (upuo *UserProfileUpdateOne) Save(ctx context.Context) (*UserProfile, error) {
	upuo.defaults()
	return withHooks(ctx, upuo.sqlSave, upuo.mutation, upuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upuo *UserProfileUpdateOne) SaveX(ctx context.Context) *UserProfile {
	node, err := upuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (upuo *UserProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := upuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upuo *UserProfileUpdateOne) ExecX(ctx context.Context) {
	if err := upuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (upuo *UserProfileUpdateOne) defaults() {
	if _, ok := upuo.mutation.UpdatedAt(); !ok {
		v := userprofile.UpdateDefaultUpdatedAt()
		upuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upuo *UserProfileUpdateOne) check() error {
	if v, ok := upuo.mutation.Firstname(); ok {
		if err := userprofile.FirstnameValidator(v); err != nil {
			return &ValidationError{Name: "firstname", err: fmt.Errorf(`ent: validator failed for field "UserProfile.firstname": %w`, err)}
		}
	}
	if v, ok := upuo.mutation.Lastname(); ok {
		if err := userprofile.LastnameValidator(v); err != nil {
			return &ValidationError{Name: "lastname", err: fmt.Errorf(`ent: validator failed for field "UserProfile.lastname": %w`, err)}
		}
	}
	if v, ok := upuo.mutation.Cmnd(); ok {
		if err := userprofile.CmndValidator(v); err != nil {
			return &ValidationError{Name: "cmnd", err: fmt.Errorf(`ent: validator failed for field "UserProfile.cmnd": %w`, err)}
		}
	}
	if v, ok := upuo.mutation.Address(); ok {
		if err := userprofile.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "UserProfile.address": %w`, err)}
		}
	}
	if v, ok := upuo.mutation.Birthday(); ok {
		if err := userprofile.BirthdayValidator(v); err != nil {
			return &ValidationError{Name: "birthday", err: fmt.Errorf(`ent: validator failed for field "UserProfile.birthday": %w`, err)}
		}
	}
	return nil
}

func (upuo *UserProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserProfile, err error) {
	if err := upuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt))
	id, ok := upuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := upuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userprofile.FieldID)
		for _, f := range fields {
			if !userprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := upuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upuo.mutation.Firstname(); ok {
		_spec.SetField(userprofile.FieldFirstname, field.TypeString, value)
	}
	if value, ok := upuo.mutation.Lastname(); ok {
		_spec.SetField(userprofile.FieldLastname, field.TypeString, value)
	}
	if value, ok := upuo.mutation.Cmnd(); ok {
		_spec.SetField(userprofile.FieldCmnd, field.TypeString, value)
	}
	if value, ok := upuo.mutation.Address(); ok {
		_spec.SetField(userprofile.FieldAddress, field.TypeString, value)
	}
	if value, ok := upuo.mutation.Gender(); ok {
		_spec.SetField(userprofile.FieldGender, field.TypeBool, value)
	}
	if value, ok := upuo.mutation.Birthday(); ok {
		_spec.SetField(userprofile.FieldBirthday, field.TypeString, value)
	}
	if value, ok := upuo.mutation.CreatedAt(); ok {
		_spec.SetField(userprofile.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := upuo.mutation.UpdatedAt(); ok {
		_spec.SetField(userprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserProfile{config: upuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, upuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	upuo.mutation.done = true
	return _node, nil
}
