// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"comb.com/banking/ent/user"
	"comb.com/banking/ent/useraccount"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAccountCreate is the builder for creating a UserAccount entity.
type UserAccountCreate struct {
	config
	mutation *UserAccountMutation
	hooks    []Hook
}

// SetAccountNumber sets the "account_number" field.
func (uac *UserAccountCreate) SetAccountNumber(s string) *UserAccountCreate {
	uac.mutation.SetAccountNumber(s)
	return uac
}

// SetBalance sets the "balance" field.
func (uac *UserAccountCreate) SetBalance(f float64) *UserAccountCreate {
	uac.mutation.SetBalance(f)
	return uac
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (uac *UserAccountCreate) SetNillableBalance(f *float64) *UserAccountCreate {
	if f != nil {
		uac.SetBalance(*f)
	}
	return uac
}

// SetUpdatedAt sets the "updated_at" field.
func (uac *UserAccountCreate) SetUpdatedAt(t time.Time) *UserAccountCreate {
	uac.mutation.SetUpdatedAt(t)
	return uac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uac *UserAccountCreate) SetNillableUpdatedAt(t *time.Time) *UserAccountCreate {
	if t != nil {
		uac.SetUpdatedAt(*t)
	}
	return uac
}

// SetUserID sets the "user" edge to the User entity by ID.
func (uac *UserAccountCreate) SetUserID(id int) *UserAccountCreate {
	uac.mutation.SetUserID(id)
	return uac
}

// SetUser sets the "user" edge to the User entity.
func (uac *UserAccountCreate) SetUser(u *User) *UserAccountCreate {
	return uac.SetUserID(u.ID)
}

// Mutation returns the UserAccountMutation object of the builder.
func (uac *UserAccountCreate) Mutation() *UserAccountMutation {
	return uac.mutation
}

// Save creates the UserAccount in the database.
func (uac *UserAccountCreate) Save(ctx context.Context) (*UserAccount, error) {
	uac.defaults()
	return withHooks(ctx, uac.sqlSave, uac.mutation, uac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uac *UserAccountCreate) SaveX(ctx context.Context) *UserAccount {
	v, err := uac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uac *UserAccountCreate) Exec(ctx context.Context) error {
	_, err := uac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uac *UserAccountCreate) ExecX(ctx context.Context) {
	if err := uac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uac *UserAccountCreate) defaults() {
	if _, ok := uac.mutation.Balance(); !ok {
		v := useraccount.DefaultBalance
		uac.mutation.SetBalance(v)
	}
	if _, ok := uac.mutation.UpdatedAt(); !ok {
		v := useraccount.DefaultUpdatedAt()
		uac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uac *UserAccountCreate) check() error {
	if _, ok := uac.mutation.AccountNumber(); !ok {
		return &ValidationError{Name: "account_number", err: errors.New(`ent: missing required field "UserAccount.account_number"`)}
	}
	if v, ok := uac.mutation.AccountNumber(); ok {
		if err := useraccount.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "UserAccount.account_number": %w`, err)}
		}
	}
	if _, ok := uac.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "UserAccount.balance"`)}
	}
	if _, ok := uac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAccount.updated_at"`)}
	}
	if len(uac.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserAccount.user"`)}
	}
	return nil
}

func (uac *UserAccountCreate) sqlSave(ctx context.Context) (*UserAccount, error) {
	if err := uac.check(); err != nil {
		return nil, err
	}
	_node, _spec := uac.createSpec()
	if err := sqlgraph.CreateNode(ctx, uac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uac.mutation.id = &_node.ID
	uac.mutation.done = true
	return _node, nil
}

func (uac *UserAccountCreate) createSpec() (*UserAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAccount{config: uac.config}
		_spec = sqlgraph.NewCreateSpec(useraccount.Table, sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt))
	)
	if value, ok := uac.mutation.AccountNumber(); ok {
		_spec.SetField(useraccount.FieldAccountNumber, field.TypeString, value)
		_node.AccountNumber = value
	}
	if value, ok := uac.mutation.Balance(); ok {
		_spec.SetField(useraccount.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := uac.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := uac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useraccount.UserTable,
			Columns: []string{useraccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_account = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserAccountCreateBulk is the builder for creating many UserAccount entities in bulk.
type UserAccountCreateBulk struct {
	config
	err      error
	builders []*UserAccountCreate
}

// Save creates the UserAccount entities in the database.
func (uacb *UserAccountCreateBulk) Save(ctx context.Context) ([]*UserAccount, error) {
	if uacb.err != nil {
		return nil, uacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uacb.builders))
	nodes := make([]*UserAccount, len(uacb.builders))
	mutators := make([]Mutator, len(uacb.builders))
	for i := range uacb.builders {
		func(i int, root context.Context) {
			builder := uacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uacb *UserAccountCreateBulk) SaveX(ctx context.Context) []*UserAccount {
	v, err := uacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uacb *UserAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := uacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uacb *UserAccountCreateBulk) ExecX(ctx context.Context) {
	if err := uacb.Exec(ctx); err != nil {
		panic(err)
	}
}
