// Code generated by ent, DO NOT EDIT.

package logintoken

import (
	"time"

	"comb.com/banking/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLTE(FieldID, id))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldToken, v))
}

// Expiredtime applies equality check predicate on the "expiredtime" field. It's identical to ExpiredtimeEQ.
func Expiredtime(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldExpiredtime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldCreatedAt, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldContainsFold(FieldToken, v))
}

// ExpiredtimeEQ applies the EQ predicate on the "expiredtime" field.
func ExpiredtimeEQ(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldExpiredtime, v))
}

// ExpiredtimeNEQ applies the NEQ predicate on the "expiredtime" field.
func ExpiredtimeNEQ(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNEQ(FieldExpiredtime, v))
}

// ExpiredtimeIn applies the In predicate on the "expiredtime" field.
func ExpiredtimeIn(vs ...time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldIn(FieldExpiredtime, vs...))
}

// ExpiredtimeNotIn applies the NotIn predicate on the "expiredtime" field.
func ExpiredtimeNotIn(vs ...time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNotIn(FieldExpiredtime, vs...))
}

// ExpiredtimeGT applies the GT predicate on the "expiredtime" field.
func ExpiredtimeGT(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGT(FieldExpiredtime, v))
}

// ExpiredtimeGTE applies the GTE predicate on the "expiredtime" field.
func ExpiredtimeGTE(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGTE(FieldExpiredtime, v))
}

// ExpiredtimeLT applies the LT predicate on the "expiredtime" field.
func ExpiredtimeLT(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLT(FieldExpiredtime, v))
}

// ExpiredtimeLTE applies the LTE predicate on the "expiredtime" field.
func ExpiredtimeLTE(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLTE(FieldExpiredtime, v))
}

// ExpiredtimeIsNil applies the IsNil predicate on the "expiredtime" field.
func ExpiredtimeIsNil() predicate.LoginToken {
	return predicate.LoginToken(sql.FieldIsNull(FieldExpiredtime))
}

// ExpiredtimeNotNil applies the NotNil predicate on the "expiredtime" field.
func ExpiredtimeNotNil() predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNotNull(FieldExpiredtime))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LoginToken {
	return predicate.LoginToken(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.LoginToken {
	return predicate.LoginToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.LoginToken {
	return predicate.LoginToken(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginToken) predicate.LoginToken {
	return predicate.LoginToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginToken) predicate.LoginToken {
	return predicate.LoginToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginToken) predicate.LoginToken {
	return predicate.LoginToken(sql.NotPredicates(p))
}
