// Code generated by ent, DO NOT EDIT.

package transfer

import (
	"time"

	"comb.com/banking/ent/predicate"
	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLTE(FieldID, id))
}

// TransactionTime applies equality check predicate on the "TransactionTime" field. It's identical to TransactionTimeEQ.
func TransactionTime(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldTransactionTime, v))
}

// From applies equality check predicate on the "From" field. It's identical to FromEQ.
func From(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldFrom, v))
}

// To applies equality check predicate on the "To" field. It's identical to ToEQ.
func To(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldTo, v))
}

// Amount applies equality check predicate on the "Amount" field. It's identical to AmountEQ.
func Amount(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldUpdatedAt, v))
}

// TransactionTimeEQ applies the EQ predicate on the "TransactionTime" field.
func TransactionTimeEQ(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldTransactionTime, v))
}

// TransactionTimeNEQ applies the NEQ predicate on the "TransactionTime" field.
func TransactionTimeNEQ(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldNEQ(FieldTransactionTime, v))
}

// TransactionTimeIn applies the In predicate on the "TransactionTime" field.
func TransactionTimeIn(vs ...time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldIn(FieldTransactionTime, vs...))
}

// TransactionTimeNotIn applies the NotIn predicate on the "TransactionTime" field.
func TransactionTimeNotIn(vs ...time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldNotIn(FieldTransactionTime, vs...))
}

// TransactionTimeGT applies the GT predicate on the "TransactionTime" field.
func TransactionTimeGT(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldGT(FieldTransactionTime, v))
}

// TransactionTimeGTE applies the GTE predicate on the "TransactionTime" field.
func TransactionTimeGTE(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldGTE(FieldTransactionTime, v))
}

// TransactionTimeLT applies the LT predicate on the "TransactionTime" field.
func TransactionTimeLT(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldLT(FieldTransactionTime, v))
}

// TransactionTimeLTE applies the LTE predicate on the "TransactionTime" field.
func TransactionTimeLTE(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldLTE(FieldTransactionTime, v))
}

// FromEQ applies the EQ predicate on the "From" field.
func FromEQ(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldFrom, v))
}

// FromNEQ applies the NEQ predicate on the "From" field.
func FromNEQ(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNEQ(FieldFrom, v))
}

// FromIn applies the In predicate on the "From" field.
func FromIn(vs ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldIn(FieldFrom, vs...))
}

// FromNotIn applies the NotIn predicate on the "From" field.
func FromNotIn(vs ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNotIn(FieldFrom, vs...))
}

// FromGT applies the GT predicate on the "From" field.
func FromGT(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGT(FieldFrom, v))
}

// FromGTE applies the GTE predicate on the "From" field.
func FromGTE(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGTE(FieldFrom, v))
}

// FromLT applies the LT predicate on the "From" field.
func FromLT(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLT(FieldFrom, v))
}

// FromLTE applies the LTE predicate on the "From" field.
func FromLTE(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLTE(FieldFrom, v))
}

// ToEQ applies the EQ predicate on the "To" field.
func ToEQ(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldTo, v))
}

// ToNEQ applies the NEQ predicate on the "To" field.
func ToNEQ(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNEQ(FieldTo, v))
}

// ToIn applies the In predicate on the "To" field.
func ToIn(vs ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldIn(FieldTo, vs...))
}

// ToNotIn applies the NotIn predicate on the "To" field.
func ToNotIn(vs ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNotIn(FieldTo, vs...))
}

// ToGT applies the GT predicate on the "To" field.
func ToGT(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGT(FieldTo, v))
}

// ToGTE applies the GTE predicate on the "To" field.
func ToGTE(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGTE(FieldTo, v))
}

// ToLT applies the LT predicate on the "To" field.
func ToLT(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLT(FieldTo, v))
}

// ToLTE applies the LTE predicate on the "To" field.
func ToLTE(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLTE(FieldTo, v))
}

// AmountEQ applies the EQ predicate on the "Amount" field.
func AmountEQ(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "Amount" field.
func AmountNEQ(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "Amount" field.
func AmountIn(vs ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "Amount" field.
func AmountNotIn(vs ...int) predicate.Transfer {
	return predicate.Transfer(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "Amount" field.
func AmountGT(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "Amount" field.
func AmountGTE(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "Amount" field.
func AmountLT(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "Amount" field.
func AmountLTE(v int) predicate.Transfer {
	return predicate.Transfer(sql.FieldLTE(FieldAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Transfer {
	return predicate.Transfer(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Transfer) predicate.Transfer {
	return predicate.Transfer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Transfer) predicate.Transfer {
	return predicate.Transfer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Transfer) predicate.Transfer {
	return predicate.Transfer(sql.NotPredicates(p))
}
